title: Vespa Documentation
lang: en
description: Installation, application user manuals, technical development topics, and more!

remote_theme: clearpathrobotics/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

